---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-app.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "simple-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Never
          name: {{ .Chart.Name }}
          env:
            - name: ROOT_PATH
              value: {{ .Values.ingress.prefixpath }}
            - name: APP_NAME
              value: {{ include "simple-app.fullname" . }}
            - name: FLUENT_HOST
              value: {{ .Values.logging.fluentHost }}
            - name: FLUENT_PORT
              value: "{{ .Values.logging.fluentPort }}"
            - name: LOG_LEVEL
              value: {{ .Values.logging.logLevel }}
          ports:
            - containerPort: {{ .Values.httpPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.httpPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources: {}
        {{- if .Values.fluent.enabled }}
        - image: "{{ .Values.fluent.image.repository }}:{{ .Values.fluent.image.tag }}"
          imagePullPolicy: Never
          name: "fluent-sidecar"
          volumeMounts:
            - name: fluent-conf-file
              mountPath: /fluentd/etc/fluent.conf
              subPath: fluentConf
              readOnly: true
            - name: elastic-certs
              mountPath: /fluentd/certs/ca.crt
              subPath: ca.crt
              readOnly: true
          livenessProbe:
            httpGet:
              path: {{ .Values.fluent.livenessProbe.httpGet.path }}
              port: {{ .Values.fluent.prometheus.containerPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
        {{- end }}
      volumes:
        - name: fluent-conf-file
          configMap:
            name: fluent-conf
            optional: true
        - name: elastic-certs
          secret:
            secretName: elasticsearch-master-certs
            optional: true
      restartPolicy: Always
status: {}
...