---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-app.selectorLabels" . | nindent 6 }}
  strategy: {}
  template:
    metadata:
      labels:
        {{- include "simple-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Never
          name: {{ .Chart.Name }}
          env:
            - name: ROOT_PATH
              value: {{ .Values.ingress.prefixpath }}
            - name: APP_NAME
              value: {{ include "simple-app.fullname" . }}
            - name: FLUENT_HOST
              value: {{ .Values.logging.fluentHost }}
            - name: FLUENT_PORT
              value: "{{ .Values.logging.fluentPort }}"
            - name: LOG_LEVEL
              value: {{ .Values.logging.logLevel }}
          ports:
            - containerPort: 6780
          livenessProbe:
            httpGet:
              path: /hello_world
              port: 6780
            initialDelaySeconds: 5
            periodSeconds: 5

          resources: {}
      restartPolicy: Always
status: {}
...