---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-app.fullname" . }}
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ include "simple-app.fullname" . }}
      port: {{ .Values.service.port }}
      targetPort: 6780
  selector:
    {{- include "simple-app.selectorLabels" . | nindent 4 }}
...