{{- if .Values.fluent.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-app.fullname" . }}-fluent-prometheus
  labels:
    {{- include "simple-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fluent.prometheus.service.type }}
  ports:
    - name: {{ include "simple-app.fullname" . }}-fluent-prometheus
      port: {{ .Values.fluent.prometheus.service.port }}
      targetPort: {{ .Values.fluent.prometheus.containerPort }}
  selector:
    {{- include "simple-app.selectorLabels" . | nindent 4 }}
...
{{- end }}