# Default values for simple-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: web
  tag: latest

nameOverride: ""
fullnameOverride: ""

logging:
  logLevel: DEBUG
  fluentHost: localhost
  fluentPort: 24224

httpPort: 6780

livenessProbe:
  httpGet:
    path: /hello_world

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  prefixpath: "/v1"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

fluent:
  enabled: true
  livenessProbe:
    httpGet:
      path: /metrics
      port: 24231

  image:
    repository: "fluentd"
    tag: "edge"
  fileConfig:
    fluentConf: |-
      <source>
        @type forward
        @id input1
        @label @mainstream
        port 24224
      </source>
      <source>
        @type prometheus
        @id input2
        bind 0.0.0.0
        port 24231
        metrics_path /metrics
      </source>
      <source>
        @type prometheus_output_monitor
        @id input3
        interval 10
        <labels>
          hostname ${hostname}
        </labels>
      </source>
      <label @mainstream>
        <match **>
          @type elasticsearch
          @log_level debug
          @id output1
          include_timestamp true
          logstash_format true
          host "elasticsearch-master"
          port 9200
          path ""
          user elastic
          password changeme
          scheme https
          ssl_verify true
          ca_file /fluentd/certs/ca.crt
        </match>
      </label>
