---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-yml
  labels:
    {{- include "prometheus-grafana.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.fileConfig }}
  {{$key }}: |-
    {{- $value | nindent 4 }}
{{- end }}
...